// BuildingNode.swift
// Features/City/
//
// 建物ノード（SpriteKit）
// - BuildingTextureGenerator で生成したテクスチャを使用（PNG アセット不要）
// - レベル Lv1〜Lv5: XP で自動昇格
// - タップ → CitySceneCoordinator.selectedBuilding 更新
// - アイソメトリック奥行き Z ポジション管理

import SpriteKit

// MARK: - BuildingNode

final class BuildingNode: SKSpriteNode {

    // MARK: - Properties

    let buildingId:   String
    let buildingName: String
    let axis:         CPAxis
    private(set) var level: Int = 1
    private(set) var xp:    Int = 0
    let gridX:        Int
    let gridY:        Int

    // XP 昇格閾値（Lv1→2: 500, Lv2→3: 1500, Lv3→4: 3000, Lv4→5: 6000）
    private static let xpThresholds = [0, 500, 1500, 3000, 6000]

    // 自動生成建物（ネガティブ表現: CLAUDE.md Key Rule 4）
    var isAutoGenerated: Bool { buildingId == "B029" || buildingId == "B030" }

    // MARK: - Init

    init(
        buildingId:   String,
        buildingName: String,
        axis:         CPAxis,
        gridX:        Int,
        gridY:        Int,
        level:        Int = 1
    ) {
        self.buildingId   = buildingId
        self.buildingName = buildingName
        self.axis         = axis
        self.gridX        = gridX
        self.gridY        = gridY
        self.level        = level

        let texture = BuildingTextureGenerator.texture(buildingId: buildingId, axis: axis, level: level)
        super.init(texture: texture, color: .clear, size: CGSize(width: 64, height: 80))

        self.isUserInteractionEnabled = true
        updateZPosition()
        playIdleAnimation()
    }

    required init?(coder aDecoder: NSCoder) { fatalError() }

    // MARK: - XP・レベルアップ

    func addXP(_ amount: Int) {
        xp += amount
        let maxLevel = BuildingNode.xpThresholds.count   // 5
        let newLevel  = (BuildingNode.xpThresholds.lastIndex { $0 <= xp } ?? 0) + 1
        let clamped   = min(newLevel, maxLevel)
        if clamped > level {
            level = clamped
            updateTexture()
            playLevelUpEffect()
        }
    }

    // MARK: - テクスチャ更新

    private func updateTexture() {
        let newTexture = BuildingTextureGenerator.texture(buildingId: buildingId, axis: axis, level: level)
        let swap = SKAction.setTexture(newTexture)
        run(swap)
    }

    // MARK: - アニメーション

    func playIdleAnimation() {
        removeAction(forKey: "idle")
        if isAutoGenerated {
            // スラム建物は揺れる
            let tilt = SKAction.sequence([
                SKAction.rotate(byAngle:  0.04, duration: 1.5),
                SKAction.rotate(byAngle: -0.04, duration: 1.5),
            ])
            run(SKAction.repeatForever(tilt), withKey: "idle")
        } else {
            // 通常建物は穏やかなボビング
            let up   = SKAction.moveBy(x: 0, y: 2, duration: 1.5)
            let down = SKAction.moveBy(x: 0, y: -2, duration: 1.5)
            up.timingMode   = .easeInEaseOut
            down.timingMode = .easeInEaseOut
            run(SKAction.repeatForever(SKAction.sequence([up, down])), withKey: "idle")
        }
    }

    private func playLevelUpEffect() {
        let pop    = SKAction.sequence([
            SKAction.scale(to: 1.35, duration: 0.12),
            SKAction.scale(to: 0.92, duration: 0.1),
            SKAction.scale(to: 1.00, duration: 0.1),
        ])
        let flash  = SKAction.sequence([
            SKAction.colorize(with: .white, colorBlendFactor: 0.9, duration: 0.08),
            SKAction.colorize(withColorBlendFactor: 0, duration: 0.15),
        ])
        run(SKAction.group([pop, flash]))

        // レベルアップラベル
        let label = SKLabelNode(text: "LEVEL UP!")
        label.fontName   = "Helvetica-Bold"
        label.fontSize   = 12
        label.fontColor  = SKColor(red: 1.0, green: 0.84, blue: 0.0, alpha: 1)
        label.position   = CGPoint(x: 0, y: 50)
        label.zPosition  = 500
        label.alpha      = 0
        addChild(label)
        label.run(SKAction.sequence([
            SKAction.group([
                SKAction.fadeIn(withDuration: 0.2),
                SKAction.moveBy(x: 0, y: 20, duration: 0.8),
            ]),
            SKAction.fadeOut(withDuration: 0.3),
            SKAction.removeFromParent(),
        ]))
    }

    func highlightBuildingZone() {
        let highlight = SKAction.sequence([
            SKAction.colorize(with: axis.skColor, colorBlendFactor: 0.6, duration: 0.15),
            SKAction.colorize(withColorBlendFactor: 0, duration: 0.25),
        ])
        run(highlight)
    }

    // MARK: - タップ → CitySceneCoordinator に通知

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        guard let scene = scene as? CityScene else { return }
        scene.coordinator?.selectedBuilding = BuildingInfo(
            id:          buildingId,
            name:        buildingName,
            axis:        axis,
            level:       level,
            description: buildingDescription,
            gridX:       gridX,
            gridY:       gridY
        )
        highlightBuildingZone()
    }

    // MARK: - 建物説明（BuildingCatalog から取得）

    private var buildingDescription: String {
        BuildingCatalog.all.first { $0.id == buildingId }?.description
            ?? "\(buildingName) Lv.\(level)"
    }

    // MARK: - Z ポジション（アイソメトリック奥行き）

    func updateZPosition() {
        zPosition = CGFloat(gridX + gridY) + (isAutoGenerated ? -10 : 0)
    }
}

// MARK: - CPAxis → SKColor（SpriteKit 用）

extension CPAxis {
    var skColor: UIColor {
        switch self {
        case .exercise:  return UIColor(red: 0.20, green: 0.78, blue: 0.35, alpha: 1)
        case .diet:      return UIColor(red: 1.00, green: 0.58, blue: 0.00, alpha: 1)
        case .alcohol:   return UIColor(red: 0.69, green: 0.32, blue: 0.87, alpha: 1)
        case .sleep:     return UIColor(red: 0.00, green: 0.48, blue: 1.00, alpha: 1)
        case .lifestyle: return UIColor(red: 1.00, green: 0.18, blue: 0.33, alpha: 1)
        }
    }
}
